Разумная болезнь опять
space-sunrise/space-station-14 pull request #157
Opened 2024-06-27 12:59 UTC by Lgibb18

теперь разумная болезнь работает и код стал адекватнее
![vihidniy](https://github.com/space-sunrise/space-station-14/assets/65973111/a9b5f9cc-663b-4686-9cdd-68f735b8a08b)

2024-06-27 13:09 UTC, Lgibb18 commented
бля, забыл кое-что

2024-06-27 13:24 UTC, Lgibb18 commented
теперь точно всё

2024-06-27 19:13 UTC, Rinary1 commented
> теперь точно всё

у тебя не билдиться хд

2024-06-27 19:26 UTC, Rinary1 commented on Content.Server/Ligyb/DiseaseRoleSystem.cs
StoreComponent в content.shared.store.components;

2024-06-27 21:18 UTC, VigersRay requested changes
Давай нормальную структуру, создай в  _Sunrise директорию Disease или чёт такое, без этих именных папок.
Если каждый начнет под себя папки делать - будет помойка.

2024-08-14 18:53 UTC, VigersRay approved these changes

2024-08-14 19:17 UTC, merged