Расширение огнестрела
space-sunrise/space-station-14 pull request #195
Opened 2024-07-13 10:58 UTC by pxc1984

## Кратное описание

Добавил огнестрел из колониальных морпехов Sunrise

## По какой причине

## Медиа(Видео/Скриншоты)

![image](https://github.com/user-attachments/assets/38e8e662-b355-4f3d-82b1-9fdf6cbdacc4)

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: pacable
- add: Добавлено 44 новых вида вооружения
- tweak: Стандартное вооружение СБ изменено
- tweak: Стандартное вооружение охраны КТ изменено

2024-07-15 11:44 UTC, VigersRay requested changes
Сделай нормальную структуру

2024-07-25 12:30 UTC, Rinary1 commented
у меня ещё есть предложение ставить патромат в сб, ибо вендомат есть в игре но его нигде не используют

2024-07-25 14:18 UTC, VigersRay commented
> у меня ещё есть предложение ставить патромат в сб, ибо вендомат есть в игре но его нигде не используют.
> 
> (вендомат с патронами, ключая учебные, резиновые и летальные)

Он всегда стоял на шаттле ОБР оффов

2024-07-26 07:48 UTC, Rinary1 commented
> Он всегда стоял на шаттле ОБР оффов

ну на данный момент на сервере его вообще не используют(на новых шаттлах обр его нет, в сб отделе его нет)

2024-07-28 23:34 UTC, VigersRay requested changes
конфликты надо решить

2024-07-31 02:54 UTC, merged