Добавил 2 новых стартгира ОСЩу, перевод ID-карт КТ, перевод пояса СБ КТ
space-sunrise/space-station-14 pull request #231
Opened 2024-07-21 21:06 UTC by VoidVepayn

## Кратное описание
Добавил 2 новых стартгира для ОСЩей, перевёл описание ID-карт сотрудников КТ, а также нейм ID-карты охранника КТ + перевод пояса СБ КТ

## По какой причине
Перевод нужен всегда, 2 стартгира для ОСЩей нужны для ПЦК

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

2024-07-23 20:28 UTC, pxc1984 requested changes
допереводы вещей желательно сделать через локализацию и не лезть в прототипы. также я не вижу спавнера осщ, по-хорошему он должен быть. посмотри как он сделан у обр

2024-07-23 20:28 UTC, pxc1984 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_sunrise/entities/objects/misc/identification_cards.ftl
> +#Prison
убери эту строчку

2024-07-23 20:28 UTC, pxc1984 commented on Resources/Prototypes/_Sunrise/Entities/Clothing/Belt/belts.yml
> +  name: пояс службы безопасности
в файлы локализации бы это..

2024-07-23 20:28 UTC, pxc1984 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Devices/identification_cards.yml
> +  name: ID карта тюремного заключённого
Тоже самое, это надо через локализацию делать

2024-07-24 17:27 UTC, VigersRay requested changes
Пу-пу-пу

2024-08-01 10:18 UTC, closed without merging