Полный перевод ss14
space-sunrise/space-station-14 pull request #236
Opened 2024-07-23 17:31 UTC by Rinary1

## Кратное описание

Полный перевод разных Менюшек, Стрингов, Кнопок, Названий и прочего хлама.

## По какой причине

Упрощает игру, радует глаз, допереводит то что должно было бы быть переведённым

## Медиа(Видео/Скриншоты)

IN PROGRESS

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: Rinary
 - tweak: Полностью переведены настройки игры
 - tweak: Полностью переведены варп точки  у гостов
 - tweak: Полностью переведена менюшка персонажа(цели антагонистов, профессии)

2024-07-23 17:32 UTC, Rinary1 commented
Суть этого PR'a показать что оффы гандоны, хардкодяд названия, а я такой крутой могу это сделать переводимым хоть на арабский(а если серьезно то причина в сообщении)

2024-07-24 08:08 UTC, Rinary1 commented
Моя основная проблема это тонна гайд буков которые надо переводить(((

2024-08-07 15:20 UTC, Rinary1 commented
Временно перевёл в draft, фикшу конфликты, мерджу изменения и добавляю больше перевода

2024-08-08 11:57 UTC, Rinary1 commented
Я не пополнял скриншотами, так как было лень, перевод уже перерос в огромный пр, так что анлак, как только закончу переводить все строчки, пойду тестить на локалке играясь с переводом и скриня весь переведённый контент

2024-08-08 15:45 UTC, Rinary1 commented
КЗ будет намного позже так как я немного не разсчитал, я сегодня весь день переводил всякий шлак, а ещё остался щит код, так что скорее всего кз будет отдельным пр-ом

2024-08-11 16:12 UTC, Rinary1 commented
С переводом пока всё, фикшу хардкод перевод и единственное что я буду делать - это если будет выходить обнова, я буду актуализировать перевод, пока его не приймут, как только его приймут, займусь английским переводом

2024-08-14 17:42 UTC, VigersRay requested changes
Джонни ты видишь их? Конфлиты, они повсюду!

2024-08-14 17:44 UTC, Rinary1 commented
> Джонни ты видишь их? Конфлиты, они повсюду!

шок

2024-08-14 18:44 UTC, merged