Добавление крафта двухклинкового энергетического меча
space-sunrise/space-station-14 pull request #244
Opened 2024-07-26 17:11 UTC by Focstor

## Кратное описание

Добавляет в меню крафта двухклинковый энергетический меч. Во вкладке "оружие".
## По какой причине

Хочу убить агента, забрать его меч, совместить его меч со своим мечом. Возвращение даблы в виде крафта.
## Медиа(Видео/Скриншоты)

![Screenshot_1](https://github.com/user-attachments/assets/e8a0f381-ead0-4104-8dda-f2db877ee6dd)
## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: Focstor
- add: Добавлен крафт двухклинкового энергетического меча.

2024-07-26 22:25 UTC, VigersRay requested changes
Не вижу смысла делать это через крафт.
Мечи по лору уже имеют разьемы для соединения, никаких кабелей не нужно, достаточно тыкнуть одним мечем по второму.
При этом должна быть возможность разобрать их обратно.

2024-07-27 04:57 UTC, VigersRay commented
Вроде сборка есть, остался вопрос разборки.

2024-07-27 10:28 UTC, Focstor commented
> Вроде сборка есть, остался вопрос разборки.

Сборки меча ещё нет, пытаюсь решить краш сервера.
Ему почему-то не нравится прототип даблы.

2024-07-27 13:28 UTC, Focstor commented
> Сборки меча ещё нет, пытаюсь решить краш сервера. Ему почему-то не нравится прототип даблы.

Фиксанул крафт, осталось сделать разборку

2024-07-27 21:14 UTC, pxc1984 requested changes

2024-07-27 21:14 UTC, pxc1984 commented on Resources/Prototypes/tags.yml
> +  id: EnergySwordBiocode
Должно быть EnergySword

2024-07-27 21:14 UTC, pxc1984 commented on Resources/Prototypes/tags.yml
> +  id: EnergySwordBiocode
SERVER: 13,950s [WARN] system.construction: Prototype EnergySwordDoubleBiocode's construction component has an invalid node specified.
Пофикси варны из автотестов. Ты же просто добавил прототип, он не должен добавлять варнов..

2024-07-27 22:50 UTC, Focstor commented on Resources/Prototypes/tags.yml
> +  id: EnergySwordBiocode
Исправил вроде

2024-07-28 19:21 UTC, Focstor commented
Ну вроде всё готово

2024-07-29 03:29 UTC, VigersRay approved these changes

2024-07-29 03:29 UTC, merged