Neo
space-sunrise/space-station-14 pull request #273
Opened 2024-08-11 19:44 UTC by ketheric-thorn

## Я добавил новые виды голопаразитов. у каждого из них свои способности. к примеру, дагон может стрелять волной из дамажащих проджектайлов. я не уверен, что оно исправно работает, т.к. делал этот прототип на сборке оффов в Июне

## По какой причине

## Медиа(Видео/Скриншоты)

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я не проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

2024-08-11 19:46 UTC, ketheric-thorn commented
Виггерс, я это на конкурс отправил если что

2024-08-12 06:34 UTC, Rinary1 commented
> Виггерс, я это на конкурс отправил если что

Если это на конкурс, то где нормальная структура? Почему ты нахерачил в 1 файл как буд-то этот прототип тупо грузить надо, если ты льешь в сборку, соблюдай минимальную структуру распределяя прототипы по файлам.

2024-08-12 06:36 UTC, Rinary1 requested changes

2024-08-12 06:36 UTC, Rinary1 commented on Resources/Prototypes/NeoParasites.yml
Зачем-то запихнул иньекторы и паразитов в 1 файл, нет нормальной структуры, слишком много копипасты, вместо того что-бы делать Ctrl+C Ctrl+V, сделай Base паразита и уже через parent добавляй изменения свойственные им, а раз это голопаразиты, используй как parent того что уже есть.

2024-08-12 09:29 UTC, ketheric-thorn commented on Resources/Prototypes/NeoParasites.yml
в конкурсе сказано, что файл доработают сначала. 
После конца конкурса, если я займу 1-3 место, я доработаю пулл

2024-08-12 09:34 UTC, Rinary1 commented on Resources/Prototypes/NeoParasites.yml
> в конкурсе сказано, что файл доработают сначала. После конца конкурса, если я займу 1-3 место, я доработаю пулл

это не означает что достаточно надрочить в 1 файл Ctrl + C Ctrl + V  и отмазываться словами "я потом доработаю", конкурс огласили ещё 23 числа, за 20 дней можно было бы и постараться. Тем более, кто возьметься доделывать твой прототип?

2024-08-12 10:16 UTC, ketheric-thorn commented on Resources/Prototypes/NeoParasites.yml
> > в конкурсе сказано, что файл доработают сначала. После конца конкурса, если я займу 1-3 место, я доработаю пулл
> 
> это не означает что достаточно надрочить в 1 файл Ctrl + C Ctrl + V и отмазываться словами "я потом доработаю", конкурс огласили ещё 23 числа, за 20 дней можно было бы и постараться. Тем более, кто возьметься доделывать твой прототип?

я вчера, в 9 часов увидел конкурс, вот и решил выложить свой прототип

2024-08-14 17:40 UTC, VigersRay commented on Resources/Prototypes/NeoParasites.yml
Слишком поздно отправил, но не переживай, я доделаю как будет время твоих голопаразитов и добавлю.

2024-10-30 12:31 UTC, closed without merging

2024-10-30 12:31 UTC, VigersRay commented
Открыт новый ПР где их доработают.