Перцовый баллончик
space-sunrise/space-station-14 pull request #319
Opened 2024-08-26 10:23 UTC by pxc1984

:cl: pacable
- add: Добавлен перцовый баллончик в игру
- tweak: Слезоточивый газ теперь при контакте с кожей вызывает тот же эффект, что и при вдыхании
- tweak: У фелинидов теперь по умолчанию перцовый баллончик в рюкзаке
- fix: Фелиниды теперь не перышки!

2024-08-28 17:03 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Loadouts/Miscellaneous/pepperspray.yml
> +    - Felinid
Не лучше ли сделать это просто предметом для всех, условно после достижения 10 часов игры на сб, у тебя открывается перцовый баллончик?

2024-08-28 17:07 UTC, pxc1984 commented on Resources/Prototypes/_Sunrise/Loadouts/Miscellaneous/pepperspray.yml
> +    - Felinid
хз, мне именно фелиниды жаловались. Типо их подбирали и чуть ли не насиловали.

2024-08-28 17:20 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Loadouts/Miscellaneous/pepperspray.yml
> +    - Felinid
> хз, мне именно фелиниды жаловались. Типо их подбирали и чуть ли не насиловали.

Так это работа модераторов это предотвращать, перцовка им не поможет, их всёравно будут брать.

2024-08-28 19:29 UTC, VigersRay requested changes
Прецовый балон должен быть только для СБ.

2024-08-30 18:18 UTC, VigersRay approved these changes

2024-08-30 18:26 UTC, merged