Новый UI
space-sunrise/space-station-14 pull request #332
Opened 2024-08-29 05:47 UTC by babaevlsdd

## Кратное описание
 меняет стиль кнопок на более современный что-ли?

## По какой причине

## Медиа(Видео/Скриншоты)

до:
![photo_2024-08-29_11-43-57](https://github.com/user-attachments/assets/2ace44fe-222e-4dc6-b80e-46c10953a5c5)

после:
![IMG_20240829_114603_569](https://github.com/user-attachments/assets/3176aa82-bac0-46e9-90ab-0a8deaef3e17)

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

:cl: Babaev
- tweak: Изменен стиль кнопок.

2024-08-29 07:41 UTC, pxc1984 commented
ну такое, на самом деле...
стало только хуже..

2024-08-29 11:36 UTC, Rinary1 commented
Да, стало явно хуже. В сравнении до, после, лучше ничего не менять либо сделать закругление

2024-08-29 12:54 UTC, VigersRay requested changes
Кнопки мы поменяли на закругленные, а окна так и остались угловые. Раз говоришь А, говори и Б, иначе как-то странно выглядит.

2024-09-16 13:17 UTC, VigersRay commented
Я доделал это сам и залил в билд.

2024-09-16 13:17 UTC, closed without merging