New drugs/desoantizyne 2.0
space-sunrise/space-station-14 pull request #336
Opened 2024-08-29 14:57 UTC by RaMbUtAn1337

## Кратное описание
Добавить новый наркотик - Дезоантизин. Сложен в исполнении, но универсален в применении. Передоз - 10 юнитов, ускорение - 1.5х, не даёт баффов к нокдауну и оглушению.

Добавить химикам новое "веселье", а антагам мотивацию к и варке всякой всячины.
## По какой причине
Объяснил выше.

## Медиа(Видео/Скриншоты)

## Проверки

- [ ] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

2024-08-29 14:57 UTC, RaMbUtAn1337 commented
:cl: RaMbUt878
- add: Добавлен Дезоантизин.

2024-08-29 16:23 UTC, deBurboun commented
Зачем ты файлы оффов редачишь? Кидай свой мусор в _Sunrise чтоб вигерсу не надо было тыкать много

2024-08-29 16:32 UTC, Rinary1 commented
> 🆑 RaMbUt878
> 
> * add: Добавлен Дезоантизин.

ченджлог нужно кидать в описание пр-а, нет скриншотов. Нет подробного рецепта.

2024-08-29 16:37 UTC, Rinary1 requested changes
Многие решения спорные, да, не стоит упускать что ты новичек, но в любом случае это детские ошибки, так-же нет корректного перевода, и правильного написания описания пр-а. Хоть и многие принебригают оформлением. Это правда ускоряет работу с ними.

2024-08-29 16:37 UTC, Rinary1 commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +    Ipecac: 2
зачем? верни на 150 строку, как было, вместо того что-бы закидывать в самое начало, это создает конфликты

2024-08-29 16:37 UTC, Rinary1 commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +    Desoantizyne: 0.75
как писал бурбон, кидай в Resources/Prototypes/_Sunrise/Recipes/Reactions/medicinde.yml, а не в оффовские файлы. Так-же вызывает не нужные конфликты

2024-08-29 16:37 UTC, Rinary1 commented on Resources/Prototypes/Reagents/narcotics.yml
> +          min: 30
Аналогично, кидай в Resources/Prototypes/_Sunrise/Reagents/narcotics.yml

Вместо наново описывания эфедрина лучше используй parent. ибо ты буквально скопировал его.

2024-08-30 07:25 UTC, Rinary1 approved these changes

2024-08-30 10:55 UTC, Rinary1 commented
> В чем разница между этим и #335
> 
> И где чейнжлог?

этот сделанный мною, 100% готовый и исправленный

2024-09-16 09:11 UTC, closed without merging