Мелкие изменения
space-sunrise/space-station-14 pull request #345
Opened 2024-08-30 18:50 UTC by Rinary1

## Кратное описание

- Добавление огромного двигателя(3x3)
- Изменение нескольких лого под стиль проекта
- Гайдбук Терминатора

## По какой причине

## Медиа(Видео/Скриншоты)

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: Rinary
 - add: Терминатор добавлен в гайдбук мелких антагонистов
 - add: Добавлен огромный двигатель, 3x3
 - tweak: Изменен большой логотип под стиль санрайза

2024-08-30 18:50 UTC, Rinary1 commented
Это надо тестить, захламить ещё барахлецом и думаю можно будет вывести с драфта

2024-09-06 08:20 UTC, Rinary1 commented
Я уехал, буду только 15 числа, так что этот пр оставлю в таком состоянии, я считаю его готовым, все остальные правки по типу актуализации локализации и вендинг автомат клоунских штучек будет уже 15.06

2024-09-16 08:15 UTC, VigersRay requested changes
конфликты

2024-09-16 08:35 UTC, Rinary1 commented
> конфликты

Я не смогу их решить ближайших 3-4 часа

2024-09-16 10:15 UTC, VigersRay commented
> > конфликты
> 
> Я не смогу их решить ближайших 3-4 часа

Давай по факту, делать апстрим вместе с какими-то своими штучками плохая затея. После мержа все эти комиты других людей станут одним большим твоим, поэтому сделай как-то раздельно.
Ну и апстрим я уже накатил в мастер самый свежий.

2024-09-16 10:23 UTC, Rinary1 commented
> Давай по факту, делать апстрим вместе с какими-то своими штучками плохая затея. После мержа все эти комиты других людей станут одним большим твоим, поэтому сделай как-то раздельно.
> Ну и апстрим я уже накатил в мастер самый свежий.
Я просто откачу мерджи ибо мои изменения не затрагивают их

2024-09-16 11:06 UTC, VigersRay commented
> > Давай по факту, делать апстрим вместе с какими-то своими штучками плохая затея. После мержа все эти комиты других людей станут одним большим твоим, поэтому сделай как-то раздельно.
> > Ну и апстрим я уже накатил в мастер самый свежий.
> 
> Я просто откачу мерджи ибо мои изменения не затрагивают их

Заливать обнову я буду ближе к вечеру, так что желательно чтобы ты успел.

2024-09-16 11:15 UTC, Rinary1 commented
> Заливать обнову я буду ближе к вечеру, так что желательно чтобы ты успел.
> 
Я вернусь домой через 10 минут, сделаю реверты, мерджну мейн ветку и ще раз проверю перевод и все, я тебе в дс напишу как закончу, думаю это будет к 16-17

2024-09-16 16:05 UTC, VigersRay approved these changes

2024-09-16 16:05 UTC, merged