Улучшение пиратского акцента
space-sunrise/space-station-14 pull request #375
Opened 2024-09-10 15:53 UTC by kanopus952

## Кратное описание

Поправить локализацию и добавить новые замены
## По какой причине

Предложка https://discordapp.com/channels/1253315855731916821/1277300495983050752/1277300495983050752
## Медиа(Видео/Скриншоты)

## Проверки

- Я не требую помощи для завершения PR
- Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

- fix: Исправлена локализация пиратского акцента
- add: Добавлены новые замены в пиратский акцент

2024-09-11 11:52 UTC, Rinary1 requested changes
В целом прикольно, но нужно внести немного правок

2024-09-11 11:52 UTC, Rinary1 commented on Resources/Locale/ru-RU/_strings/accent/pirate.ftl
> -accent-pirate-replacement-32 = порох
уберать реплейсмент патронов не стоит

2024-09-11 11:52 UTC, Rinary1 commented on Resources/Locale/ru-RU/_strings/accent/pirate.ftl
> -accent-pirate-replacement-28 = сухопутный
с грейтайдами тоже, оставь, у нас этот термин как и у оффов есть, просто дополни, грейтайдер, тайдер = сухопутный

2024-09-11 11:52 UTC, Rinary1 commented on Resources/Prototypes/Accents/word_replacements.yml
>  - type: accent
Энд не добавил(комментарий)

2024-09-11 18:14 UTC, kanopus952 commented on Resources/Locale/ru-RU/_strings/accent/pirate.ftl
> -accent-pirate-replacement-32 = порох
Я вроде не хотел ее убирать, но забыл..

2024-09-11 18:15 UTC, kanopus952 commented on Resources/Locale/ru-RU/_strings/accent/pirate.ftl
> -accent-pirate-replacement-28 = сухопутный
Угу

2024-09-11 18:16 UTC, kanopus952 commented on Resources/Prototypes/Accents/word_replacements.yml
>  - type: accent
Понял

2024-09-12 11:44 UTC, kanopus952 commented on Resources/Locale/ru-RU/_strings/accent/pirate.ftl
> -accent-pirate-replacement-32 = порох
all done!

2024-09-16 08:09 UTC, merged