Dedsquad
space-sunrise/space-station-14 pull request #382
Opened 2024-09-14 16:55 UTC by DragonDidlo

## Кратное описание
Представляю вашему вниманию Лорный Эскадрон Смерти.
Это не те ванильные сосунки, это те парни, которые всего в три бойца могут спокойно уложить 20 элитных бойцов Горлакса!

## Список отличий 
Чем именно эти Деды отличаются от Ванильных?
- Своей, не прослушиваемой частотой [:э].
- Своей фракцией (Для турелей).
- Своими турели которые по всем стреляют (Баллистическая и Импульсная).
- Вооружением и Снаряжением, которое имеет Биокодировку в связи с которой, никто кроме Дедов не может его использовать.
- Улучшенным хват вооружения ДСО, в связи с которым обычный человек не сможет выбить оружие из рук Деда.
- Увеличенной стаминой (Держат в 2-3 раза больше выстрелов со станера или ударов дубинки чем обычный экипаж станции).
- Увеличенным болевым порогом (Падают в крит при 150 уроне, а умирают при 200).
- Имплантом усилителя рук (Могут вскрывать двери без лома, так же как и враждебные мобы).
- Имплантом жизни (Регенерирует в телах Дедов супер стимулятор в малых дозах = Пассивный хилл + Быстрое поднятие после стана).
- Начальным иммунитетом от Вирусов (Игнорирует Зомби заразу).
- Отсутствием голода.
- Своими уникальными структурами (Крепкий двигатель который не отключить просто так, двери с доступом ДСО и консоль связи ДСО).
- Своим мини шаттлом для доставки оперативников на объект операции.

**Путь до шаттла:** /Maps/_Sunrise/Shuttles/death_squad_pod.yml

## По какой причине
1) Отключили загрузку прототипов.
2) Многим игрокам понравился данный Эскадрона Cмерти.
3) Для будущего аванпоста ДСО.
4) Ванильный Эскадрон Смерти очень слабый.

## Медиа(Видео/Скриншоты)
![image](https://github.com/user-attachments/assets/172bcb1b-28d4-47b7-82d6-0551f4cdf8d3)
![image](https://github.com/user-attachments/assets/1fb83a58-e055-4c5b-b1ee-be587aaa643e)
![image](https://github.com/user-attachments/assets/69c52494-4645-49db-a821-8f82923d30d8)
![image](https://github.com/user-attachments/assets/28f5f76e-5e2b-4068-8a57-3fcbf333c254)

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**
:cl: Parashut
- add: Добавлены улучшенные Оперативники Эскадрона Смерти.
- add: Добавлен мини шаттл для Эскадрона Смерти.

2024-09-16 09:36 UTC, CatBackGround commented
Бьюсь об заклад, вы спёрли пару идей из одного прототипа...

2024-09-16 09:37 UTC, DragonDidlo commented
Какого?

2024-09-16 17:03 UTC, DragonDidlo commented
И чё за конфликт то бля.

2024-09-16 17:14 UTC, CatBackGround commented
> Какого? 

Ewer'овский прототип с похожим наполнением.

2024-09-17 19:31 UTC, DragonDidlo commented
@VigersRay конфликти пофикшены

2024-09-19 13:04 UTC, VigersRay requested changes

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Access/deathsquad.yml
Используй полные названия для айди а не сокращение.

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Markers/Spawners/jobs.yml
Спавнер по сигналу не нужен, удали его.

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Mobs/Player/deathsquad.yml
Хардкод перевод, используй ftl файлы в locale

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Objects/Clothing/deathsquad_clothing.yml
хардкод перевод

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Objects/Specific/stimulator.yml
нерфи, слишком имба.

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Guns/Ammunition/Magazines/shotgun.yml
нерфи, слишком имба.

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Guns/Biocode/biocode.yml
нерфи возможность выбить оружие из рук.

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Guns/Biocode/biocode.yml
для дедсквада стоит использовать любой другой дробвик а не бульдог. В билде куча разного огнестрела. Но в идеале вообще убрать огнестрел у дедсквада, всё же это старье.

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/deathsquad.yml
Зачем нужна такая имба если уже есть тазер?

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Structures/Shuttles/thrusters.yml
Удали это, в билде уже есть улучшеные 2х2 и 3х3 двигатели

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Reagents/narcotics.yml
имба, нерфи

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Roles/Jobs/Fun/deathsquad.yml
Сделай нормальные индетификаторы и не сокращения

2024-09-19 13:04 UTC, VigersRay commented on Resources/Prototypes/ai_factions.yml
Не надо добавлять еще одну фракцию чисто ради турельки.

2024-11-02 23:18 UTC, Mizeliy-2 commented
Мда, а ведь можно было просто сделать шаттл с небольшой оружейной.

2024-11-11 15:43 UTC, closed without merging