Питомцы
space-sunrise/space-station-14 pull request #391
Opened 2024-09-17 19:21 UTC by ThereDrD0

## Кратное описание

**Добавлена система питомцев, включающая:**

- Приручение
- Управление через круговое меню
- Возможность игроку управлять питомцем, если это захочет хозяин
- Управление поведением питомца
- Полная кастомизация возможных вариантов действий и управления

## По какой причине

Таск дали, а я сделал, прикольно че

## Медиа(Видео/Скриншоты)

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl:
- add: Добавлены питомцы

2024-09-25 14:30 UTC, RavMorgan commented
А зачем ты портировал РАДИАЛЬНОЕ меню с билда ГиедиПрайма, если оно давно уже было сделано Визардами? 
Нет смысла иметь разные реализации одной системы в проекте.

Переведи все на реализацию от Визардов и удали порт с Гиеди.
![image](https://github.com/user-attachments/assets/9c5858e3-3b98-485a-b2d9-9834686586cd)

2024-09-25 15:18 UTC, ThereDrD0 commented
> @ThereDrD0 А зачем ты портировал РАДИАЛЬНОЕ меню с билда ГиедиПрайма, если оно давно уже было сделано Визардами? 
> Нет смысла иметь разные реализации одной системы в проекте.
> 
> Переведи все на реализацию от Визардов и удали порт с Гиеди.
> Посмотреть на реализацию можешь тут - https://github.com/space-sunrise/space-station-14/blob/master/Content.Client/Chat/UI/EmotesMenu.xaml.cs
> ![image](https://github.com/user-attachments/assets/9c5858e3-3b98-485a-b2d9-9834686586cd)
> 

Мне сплик сказал, что меню виздена говно и нужно то меню с культа. Я и портировал. Оно по факту лучше, чем у виздена.
У меня изначально меню виздена и было

2024-09-25 15:40 UTC, RavMorgan commented
@ThereDrD0 
Проблема в том, что это кодеров путать будет. Нужно либо старое радиальное меню выпилить, либо внедрить функционал нового радиального меню в старое, при этом сохранив обратную совместимость.

2024-09-25 18:07 UTC, ThereDrD0 commented
> @ThereDrD0 Проблема в том, что это будет путать кодеров и засорять кодбазу. Нужно либо старое радиальное меню выпилить, либо внедрить функционал нового радиального меню в старое, при этом сохранив обратную совместимость.

Я бы просто переименовал все публичные функции новых радиалов, чтобы не возникало путаницы. Убирать радиалы виздена или их изменять = создавать проблемы при апстримах. Лучше так не делать.
Пусть будет 2 версии радиалов

2024-09-30 16:33 UTC, Rinary1 commented
супер странно добавлять 2 радиальные системы. Либо оставляйте какую-то одну, либо предлогайте свою оффам. Если она реально лучше. Они приймут.

2024-09-30 19:31 UTC, ThereDrD0 commented
> супер странно добавлять 2 радиальные системы. Либо оставляйте какую-то одну, либо предлогайте свою оффам. Если она реально лучше. Они приймут.

Эти радиалы все еще являются частью какой-то договоренностью между валтосом с Гиеди Прайм как владельца оригинального кода и Санрайза. Сейчас они тут, потому что Санрайз купил код культа крови, где были эти радиалы.
И Санрайз получил право от Валтоса публиковать радиалы тут.

А еще я не очень горю желанием проходить длительное ревью у виздена. Мне дали таск сделать петов и радиалы крутые портировать. Таск выполнен. Дальше с этими радиалами что делать решать основным кодерам базового билда санрайза

2024-09-30 19:46 UTC, Rinary1 commented
> > супер странно добавлять 2 радиальные системы. Либо оставляйте какую-то одну, либо предлогайте свою оффам. Если она реально лучше. Они приймут.
> 
> Эти радиалы все еще являются частью какой-то договоренностью между валтосом с Гиеди Прайм как владельца оригинального кода и Санрайза. Сейчас они тут, потому что Санрайз купил код культа крови, где были эти радиалы. И Санрайз получил право от Валтоса публиковать радиалы тут.
> 
> А еще я не очень горю желанием проходить длительное ревью у виздена. Мне дали таск сделать петов и радиалы крутые портировать. Таск выполнен. Дальше с этими радиалами что делать решать основным кодерам базового билда санрайза

ого как круто, таск дали тебе, но при этом разбираться тем которые даже не знали о том что тип вводит ещё 1 радиальную систему.

2024-09-30 21:58 UTC, ThereDrD0 commented
> > > супер странно добавлять 2 радиальные системы. Либо оставляйте какую-то одну, либо предлогайте свою оффам. Если она реально лучше. Они приймут.
> > 
> > Эти радиалы все еще являются частью какой-то договоренностью между валтосом с Гиеди Прайм как владельца оригинального кода и Санрайза. Сейчас они тут, потому что Санрайз купил код культа крови, где были эти радиалы. И Санрайз получил право от Валтоса публиковать радиалы тут.
> > 
> > А еще я не очень горю желанием проходить длительное ревью у виздена. Мне дали таск сделать петов и радиалы крутые портировать. Таск выполнен. Дальше с этими радиалами что делать решать основным кодерам базового билда санрайза
> 
> ого как круто, таск дали тебе, но при этом разбираться тем которые даже не знали о том что тип вводит ещё 1 радиальную систему.

¯\_(ツ)_/¯. 
Я могу попытаться объединить две системы радиалов в один, но если в апстриме сделают рефактор радиалов, потом нужно будет решать много конфликтов. 
Хз, по мне оно того не стоит и две разные системы радиалов, которые никак друг с другом не конфликтуют лучший вариант. А они между собой не конфликтуют, если что

2024-10-08 14:17 UTC, darvin7531 commented
Если отойти от питомца и открыть меню, то будет такой эффект.

https://youtu.be/rCMjjeP3pfY

2024-10-08 21:14 UTC, ThereDrD0 commented
> Если отойти от питомца и открыть меню, то будет такой эффект.
> 
> https://youtu.be/rCMjjeP3pfY

Баги кода виздена. Я могу это пофиксить только вернув ограничение на радиус, в котором можно открывать и взаимодействовать с меню

2024-10-09 06:19 UTC, Rinary1 commented
> > Если отойти от питомца и открыть меню, то будет такой эффект.
> > https://youtu.be/rCMjjeP3pfY
> 
> Баги кода виздена. Я могу это пофиксить только вернув ограничение на радиус, в котором можно открывать и взаимодействовать с меню

ну так, так и надо, разве нет? В любом случае должно быть ограничение на радиус действия ui, ты же не можешь уйти в космос и позвать своего питомца через 3 версты.

2024-10-09 06:44 UTC, ThereDrD0 commented
> > > Если отойти от питомца и открыть меню, то будет такой эффект.
> > > https://youtu.be/rCMjjeP3pfY
> > 
> > Баги кода виздена. Я могу это пофиксить только вернув ограничение на радиус, в котором можно открывать и взаимодействовать с меню
> 
> ну так, так и надо, разве нет? В любом случае должно быть ограничение на радиус действия ui, ты же не можешь уйти в космос и позвать своего питомца через 3 версты.

Я уберу бесконечный радиус

2024-11-19 17:14 UTC, ThereDrD0 commented
> zshdem 😢 

А кого ждёте... Все же готово

2024-11-19 17:25 UTC, pxc1984 commented
> > zshdem 😢
> 
> А кого ждёте... Все же готово

сплик говорит что могут быть проблемы с оптимизацией при добавлении по 5 питомцев на донатера

2024-11-19 17:28 UTC, ThereDrD0 commented
> > > zshdem 😢
> > 
> > А кого ждёте... Все же готово
> 
> сплик говорит что могут быть проблемы с оптимизацией при добавлении по 5 питомцев на донатера

А вы не добавляйте 5 питомцев каждому донатеру. Если какие-то проблемы с производительностью и будут, то это проблемы кода НПС, поиска их пути и всякого такого. Так можно вечно ждать, пока кто-то это оптимизирует...

2024-11-19 21:04 UTC, ThereDrD0 commented
> > > > zshdem 😢
> > > 
> > > 
> > > А кого ждёте... Все же готово
> > 
> > 
> > сплик говорит что могут быть проблемы с оптимизацией при добавлении по 5 питомцев на донатера
> 
> Таки ограничение на 1-2 петов поставить игрокам, не?

В прототипах регулируется. Игрок получает питомцев через лоадауты, просто можно выставить максимальное количество возможных питомцев взять с собой. 
Поэтому по идее должно быть 1 питомец на одного игрока. Но если питомцы подразумеваются для всех игроков - тогда да, там могут быть лаги. Условные 100 нпс на сервер ощутимую нагрузку сделают. Лучше оставить их донатерам в случае больших проблем с производительностью. Или поставить большой таймер на часы питомцам

2025-01-04 06:58 UTC, VigersRay requested changes

2025-01-04 06:58 UTC, VigersRay commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
Это рофл? Система радиального меню уже есть в игре, зачем дубль?

2025-01-04 06:58 UTC, VigersRay commented on Content.Client/_Sunrise/UserInterface/Radial/RadialButton.xaml.cs
Дубль радиала

2025-01-04 06:58 UTC, VigersRay commented on Content.Client/_Sunrise/UserInterface/Radial/RadialContainer.xaml
Дубль радиала

2025-01-04 06:58 UTC, VigersRay commented on Content.Client/_Sunrise/UserInterface/Radial/RadialContainer.xaml.cs
Дубль радиала

2025-01-04 06:58 UTC, VigersRay commented on Content.Client/_Sunrise/UserInterface/Radial/RadialButton.xaml
Дубль радиала

2025-01-04 06:58 UTC, VigersRay commented on Content.Client/_Sunrise/Radials/RadialUIController.cs
Дубль радиала

2025-01-04 06:58 UTC, VigersRay commented on Resources/Prototypes/ai_factions.yml
> +
Такая фракция уже есть у оффов

2025-01-04 06:58 UTC, VigersRay commented on Content.Shared/_Sunrise/Radials/Radial.cs
Дубль радиала

2025-01-04 06:58 UTC, VigersRay commented on Content.Shared/_Sunrise/Radials/RadialEvents.cs
Дубль радиала

2025-01-04 06:58 UTC, VigersRay commented on Content.Shared/_Sunrise/Radials/Systems/SharedRadialSystem.cs
Дубль радиала

2025-01-04 06:58 UTC, VigersRay commented on Content.Server/_Sunrise/Radials/RadialSystem.cs
Дубль радиала

2025-01-04 07:00 UTC, ThereDrD0 commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
Сплик попросил конкретно эту

2025-01-04 07:01 UTC, ThereDrD0 commented on Resources/Prototypes/ai_factions.yml
> +
Тогда не было, уберу

2025-01-04 07:01 UTC, VigersRay commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> Сплик попросил конкретно эту

А в чем между ними разница? Если надо доработай радиал оффов

2025-01-04 07:04 UTC, ThereDrD0 commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
Радиал оффов практически полностью совпадает с этим, только это лучше.
Оно намного более генерик и позволяет быстро сделать круговое меню с нужным функционалом.
Поэтому тут только вырезать меню виздена и заменять на это

2025-01-04 07:05 UTC, ThereDrD0 commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> > Сплик попросил конкретно эту
> 
> А в чем между ними разница? Если надо доработай радиал оффов

А ещё тут визуальные эффекты приятнее и возможно сделать радиал закреплённый за Ентити

2025-01-04 07:07 UTC, VigersRay commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> > > Сплик попросил конкретно эту
> > 
> > 
> > А в чем между ними разница? Если надо доработай радиал оффов
> 
> А ещё тут визуальные эффекты приятнее и возможно сделать радиал закреплённый за Ентити

Радиал оффов аналогично можно закрепить за энтити. Чекни ИИ и его управление шлюзами.

2025-01-04 07:08 UTC, VigersRay commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> Радиал оффов практически полностью совпадает с этим, только это лучше. Оно намного более генерик и позволяет быстро сделать круговое меню с нужным функционалом. Поэтому тут только вырезать меню виздена и заменять на это

Ну так замени, только сохранив оригинальное местоположение.

2025-01-04 07:08 UTC, ThereDrD0 commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> > > > Сплик попросил конкретно эту
> > > 
> > > 
> > > А в чем между ними разница? Если надо доработай радиал оффов
> > 
> > А ещё тут визуальные эффекты приятнее и возможно сделать радиал закреплённый за Ентити
> 
> Радиал оффов аналогично можно закрепить за энтити. Чекни ИИ и его управление шлюзами.

Значит уже сделали

2025-01-04 07:09 UTC, ThereDrD0 commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> > Радиал оффов практически полностью совпадает с этим, только это лучше. Оно намного более генерик и позволяет быстро сделать круговое меню с нужным функционалом. Поэтому тут только вырезать меню виздена и заменять на это
> 
> Ну так замени, только сохранив оригинальное местоположение.

Ок, но это создаст анальную боль при мержах с виздена, если они будут использовать радиалы

2025-01-04 07:11 UTC, VigersRay commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> > > Радиал оффов практически полностью совпадает с этим, только это лучше. Оно намного более генерик и позволяет быстро сделать круговое меню с нужным функционалом. Поэтому тут только вырезать меню виздена и заменять на это
> > 
> > 
> > Ну так замени, только сохранив оригинальное местоположение.
> 
> Ок, но это создаст анальную боль при мержах с виздена, если они будут использовать радиалы

Использовать - нет
Рефакторить - да
Ты же не будешь ломать старые использования радиалов оффов?
Кстати там у культа крови используется радиал оффов, глянь как я его заюзал.

2025-01-04 07:15 UTC, ThereDrD0 commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
Тут система построения радиала другая. Посмотри коммит, где я их добавил. Там я поменял в системе радиал оффов на новый. Код сократился раза в 4. Если заменять радиалы, то нужно будет во всех местах переделывать таким образом.

Мой вариант был сохранить 2 вида радиалов, чтобы не переделывать код виздена по всей кодбазе на новый радиалы. Они между собой не конфликтуют, можно использовать как новые, так и виздена спокойно

2025-01-04 07:49 UTC, VigersRay commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> Тут система построения радиала другая. Посмотри коммит, где я их добавил. Там я поменял в системе радиал оффов на новый. Код сократился раза в 4. Если заменять радиалы, то нужно будет во всех местах переделывать таким образом.
> 
> Мой вариант был сохранить 2 вида радиалов, чтобы не переделывать код виздена по всей кодбазе на новый радиалы. Они между собой не конфликтуют, можно использовать как новые, так и виздена спокойно

Логично блядь что код сократился, ты же перенес всю логику внутрь системы.

2025-01-04 07:50 UTC, VigersRay commented on Content.Client/_Sunrise/Radials/RadialSystem.cs
> Тут система построения радиала другая. Посмотри коммит, где я их добавил. Там я поменял в системе радиал оффов на новый. Код сократился раза в 4. Если заменять радиалы, то нужно будет во всех местах переделывать таким образом.
> 
> Мой вариант был сохранить 2 вида радиалов, чтобы не переделывать код виздена по всей кодбазе на новый радиалы. Они между собой не конфликтуют, можно использовать как новые, так и виздена спокойно

Ладно бы если данная система была 1 файлом как лейджоин, но тут дохуя, лучше адаптировать систему оффов. 
В будущем + вероятно у оффов радиалы будут лучше.

2025-01-11 04:53 UTC, VigersRay approved these changes
Сыровато но похуй, доделаем на проде.

2025-01-11 04:53 UTC, merged