Добавление в меню покупок карго новой хуйни
space-sunrise/space-station-14 pull request #405
Opened 2024-09-27 01:10 UTC by Focstor

## Кратное описание

Добавил в меню покупок карго следующее:
M16A4
AKMS
MP5
Боевые изолированные перчатки
Армейский РПС
Ящик патронов .30
Ящик патронов .20
## По какой причине

хочу. Часто вижу, что СБ не запрашивает покупки в карго. Из-за хуёвости выбора, ибо там всё говно.
## Медиа(Видео/Скриншоты)

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: Focstor
- add: M16A4 теперь можно купить в карго.
- add: AKMS теперь можно купить в карго.
- add: MP5 теперь можно купить в карго.
- add: Боевые изолированные перчатки теперь можно купить в карго.
- add: Армейский РПС теперь можно купить в карго.
- add: Ящик патронов .30 калибра теперь можно купить в карго.
- add: Ящик патронов .20 калибра теперь можно купить в карго.

2024-09-27 07:47 UTC, Rinary1 requested changes
хуйня, переделывай

2024-09-27 07:47 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/Cargo/cargo_security.yml
> +  cost: 1500
1500 за 3 пары? Слишком дешево, поднимай цену хотя-бы x2-x2.5(3000-4500)

2024-09-27 07:47 UTC, Rinary1 commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
>    description: A set of tactical webbing worn by Syndicate boarding parties.
С каких пор это сб?

2024-09-27 07:47 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/Fills/Crates/security.yml
> +        amount: 1
Хуйня, делай не армейское рпс а рпс охраны. Армейское рпс соло синдикатовское(смотри описание)

2024-09-27 07:47 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/Cargo/cargo_armory.yml
> +  group: market
слишком дорого, легче купить за 1500 ящик стали где за 3 стака в охранном тех.фабе можно скрафтить 300 винтовочных, никто не будет это покупать

2024-09-27 07:47 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/Cargo/cargo_armory.yml
> +  group: market
аналогично высказыванию выше, легче купить стали на 1500, и скрафтить 600 патрон что равно 3 коробам, тут-же продаеться 2 короба за 5000, выходит что типы уйдут в огромный минут покупая патроны на скорость

2024-09-27 07:47 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/Fills/Crates/armory.yml
> +        amount: 2
2 мало, выше высказал почему, делай 3 короба за 2000

2024-09-27 07:47 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/Fills/Crates/armory.yml
> +        amount: 2
аналогично, 3 короба за 2000

2024-09-27 09:25 UTC, Focstor commented on Resources/Prototypes/_Sunrise/Catalog/Fills/Crates/security.yml
> +        amount: 1
РПС охраны хуйня из-за вайтлиста. Армейский РПС носят не только синдикатовцы.

2024-09-27 09:29 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/Fills/Crates/security.yml
> +        amount: 1
> Contributor

только синдикат, убирай вайтлист на рпс охраны и делай ее, армейская рпс это шмотка синдиката.

2024-09-27 09:30 UTC, Focstor commented on Resources/Prototypes/_Sunrise/Catalog/Fills/Crates/security.yml
> +        amount: 1
В игре существует РПС синдиката

2024-09-27 09:34 UTC, Focstor commented on Resources/Prototypes/_Sunrise/Catalog/Fills/Crates/security.yml
> +        amount: 1
Значит уберу вайтлист у РПС охраны и верну армейский РПС на своё место

2024-09-27 10:46 UTC, Rinary1 approved these changes

2024-09-27 13:47 UTC, kanopus952 commented
Можешь сразу добавить слаймов для закупки? Желательно сделать их безобидными. Они часто требуется для цели, а получить их можно не всегда

2024-09-27 19:26 UTC, Rinary1 requested changes

2024-09-27 19:26 UTC, Rinary1 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
Не городи все в 1 пр, это плохо, вигерс такое не любит

2024-09-27 19:29 UTC, Focstor commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
> Не городи все в 1 пр, это плохо, вигерс такое не любит

Ужасы, больше не буду

2024-09-30 13:15 UTC, VigersRay approved these changes

2024-09-30 13:15 UTC, merged