Новые звуки, снова
space-sunrise/space-station-14 pull request #463
Opened 2024-10-06 06:38 UTC by kanopus952

## Кратное описание

Добавил звук вызова\отклонения ОБР, 5 уровень биологической угрозы и удар БС артиллерии. Еще заменил начальный саунд эпсилона на трэк от болгарыча, он звучит просто отлично
## По какой причине

Звуки попросил добавить один из модеров
## Медиа(Видео/Скриншоты)

## Проверки

- [✅] Я не требую помощи для завершения PR
- [✅] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [✅] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: kanopus7
- add: Добавлены новые звуки для админов.
- tweak: Изменен звук кода эпсилон.

2024-10-06 07:19 UTC, Rinary1 commented
> ## Проверки
> * [✅] Я не требую помощи для завершения PR
> * [✅] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
> * [✅] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

Проверки через x Ставяться:

- [x] пу=-пу-пу

2024-10-06 07:28 UTC, kanopus952 commented
а, буду знать

2024-10-06 22:16 UTC, VigersRay requested changes
Эти звуки с корвакса и абсолютно не сочетаются с нашим голосом озвучки оповещений. Если ты хочешь их использовать тебе нужно заменить здесь голос на тот что обычно используется для оповещений... Такие дела.

2024-10-07 15:58 UTC, kanopus952 commented
благодаря rinary обновил

2024-10-08 07:37 UTC, VigersRay requested changes

2024-10-08 07:37 UTC, VigersRay commented on Resources/Prototypes/AlertLevels/alert_levels.yml
Я не особо понимаю нахуя сигнал епсилона менять на музон, какой в этом смысл? Если так хочется то админы сами могут эту музыку запустить, но звук кода должен быть коротким.

2024-10-08 07:46 UTC, Rinary1 commented
Да, музон действительно лишний. Если его и добавлять то добавлять в связке с системой алертов из сс13(по мере увеличивания кода меняеться надпись на экранах, в эпсилон вырубаеться свет и тд)

2024-10-09 12:48 UTC, kanopus952 commented on Resources/Prototypes/AlertLevels/alert_levels.yml
эпсилон - завершение раунда, как в случае с ядеркой. Там есть музон, а для эпсилона - нет. Энивей, видел такое на империале, никому вроде не мешало и даже более атмосферно было. Но если настаиваете.. без проблем уберу

2024-10-10 15:29 UTC, kanopus952 commented on Resources/Prototypes/AlertLevels/alert_levels.yml
все, убрал

2024-10-10 17:06 UTC, merged