tweaks.
space-sunrise/space-station-14 pull request #465
Opened 2024-10-06 11:08 UTC by rhailrake

2024-10-06 13:15 UTC, Rinary1 requested changes

2024-10-06 13:15 UTC, Rinary1 commented on Content.Server/GameTicking/GameTicker.RoundFlow.cs
зачем? Для кого придумали станционный якорь?

2024-10-06 13:15 UTC, Rinary1 commented
описания нет...

2024-10-07 00:49 UTC, VigersRay approved these changes

2024-10-07 05:45 UTC, merged