БИОКОД на энерго щитах
space-sunrise/space-station-14 pull request #472
Opened 2024-10-08 07:18 UTC by Rinary1

## Кратное описание

Добавлен биокод на энерго щиты синдиката, что-бы предотвратить использование их во благо станции(fixes #467)

## По какой причине

Баг

## Медиа(Видео/Скриншоты)

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl:
- tweak: Теперь энерго щиты синдиката имеют биокод

2024-10-08 07:39 UTC, VigersRay requested changes
А проблема аналогичная энерго мечам здесь наблюдается? (Включеный меч можно подобрать и отражать ним снаряды даже если на нем биокод)

2024-10-08 07:41 UTC, Rinary1 commented
> А проблема аналогичная энерго мечам здесь наблюдается? (Включеный меч можно подобрать и отражать ним снаряды даже если на нем биокод)

Да. Я не правил код биокода. Надо писать отдельную систему для ItemToggle

2024-10-08 07:46 UTC, VigersRay commented
> > А проблема аналогичная энерго мечам здесь наблюдается? (Включеный меч можно подобрать и отражать ним снаряды даже если на нем биокод)
> 
> Да. Я не правил код биокода. Надо писать отдельную систему для ItemToggle

Ну вообще, я считаю что меч не может быть априори включен когда он не в руках. Нужно трогать саму систему энергомеча чтобы при вылетании с руки или выбрасывании он выключался.
Включить меч никто не сможет, аналогично с щитами.

2024-10-08 09:38 UTC, Rinary1 commented
> > > А проблема аналогичная энерго мечам здесь наблюдается? (Включеный меч можно подобрать и отражать ним снаряды даже если на нем биокод)
> > 
> > 
> > Да. Я не правил код биокода. Надо писать отдельную систему для ItemToggle
> 
> Ну вообще, я считаю что меч не может быть априори включен когда он не в руках. Нужно трогать саму систему энергомеча чтобы при вылетании с руки или выбрасывании он выключался. Включить меч никто не сможет, аналогично с щитами.

по щитам, довольно спорно, аргументирую это переносным щитом, ну и что мешает типу не надевая агрегат влючить его? На счёт меча согласен. На счёт щитов - явно нет

2024-10-10 17:07 UTC, VigersRay approved these changes

2024-10-10 17:07 UTC, merged