Добавлен переделанный шатл ОБРовцов
space-sunrise/space-station-14 pull request #495
Opened 2024-10-12 09:55 UTC by imskyhappy

:cl: SkyHappy
- add: Добавлен переделанный шаттл для ОБРовцов.

2024-10-12 10:08 UTC, Rinary1 requested changes
убирай лишнее

2024-10-12 10:08 UTC, Rinary1 commented on Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
> +      roleLoadout: [ RoleSurvivalStandard ]
это что такое?

2024-10-13 06:48 UTC, Rinary1 approved these changes

2024-10-13 12:23 UTC, pxc1984 commented
Locale validator braindead

2024-10-30 07:03 UTC, merged