Добавил роль Офицер «Синий Щит»
space-sunrise/space-station-14 pull request #5
Opened 2024-06-01 14:38 UTC by SplikZerys

2024-06-05 09:33 UTC, VigersRay commented
![image](https://github.com/space-sunrise/space-station-14/assets/60344369/afd4ec00-f36c-476f-968a-af1ff88a2dab)
Закинь это в _Sunrise создав новые .yml если надо. Лишние конфликты ни к чему.
И синий щит должен быть в департаменте синего щита, как и было раньше.

2024-06-08 18:23 UTC, VigersRay requested changes
Нужно перенести всё что можно в _Sunrise во избежание конфликтов и создать департамент "Синего щита".

2024-06-09 14:05 UTC, Rinary1 commented
> ![image](https://private-user-images.githubusercontent.com/60344369/336778061-afd4ec00-f36c-476f-968a-af1ff88a2dab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDIxMzcsIm5iZiI6MTcxNzk0MTgzNywicGF0aCI6Ii82MDM0NDM2OS8zMzY3NzgwNjEtYWZkNGVjMDAtZjM2Yy00NzZmLTk2OGEtYWYxZmY4OGEyZGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE0MDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxODUxNDc2NjAyZmFkODg3OTZhZGI0ZTFiOWY0MTE2NDM1NmNkYjhiOWU2MDQyZDNlOTVjMzUwZDQwZDFkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HuzUJRkz3I07bxPHnjLaQd7X7uxwNR_CRFnGrvfCkUA) Закинь это в _Sunrise создав новые .yml если надо. Лишние конфликты ни к чему. И синий щит должен быть в департаменте синего щита, как и было раньше.

есть предложение закинуть в департамент "Представителей Центрального Коммандования", туда будет входить синий щит, пцк, и другие представители центрального коммандования которые будут спавниться сразу на станции

2024-06-12 11:19 UTC, VigersRay commented
Более свежий https://github.com/space-sunrise/space-station-14/pull/60

2024-06-12 11:19 UTC, closed without merging