Мелкие изменения в мехах
space-sunrise/space-station-14 pull request #507
Opened 2024-10-13 14:21 UTC by Rinary1

**Changelog**

:cl: Rinary
- fix: Исправлен залаз существ в меха которые не имеют рук.
- fix: Исправлены нпс которые не били мехов

2024-10-13 17:48 UTC, KaiserMaus commented
Можешь повысить время которое нужно чтобы вытащить человека из МЕХа?

2024-10-16 22:29 UTC, KaiserMaus commented
Что на счёт Гиппо дротика и стрел с копиями? Они работают как пирс введение?

2024-10-20 07:49 UTC, pxc1984 commented
имба чейнджлог 👍

2024-10-22 10:11 UTC, Rinary1 commented
> имба чейнджлог 👍

Да, не плох

2024-10-22 10:20 UTC, KaiserMaus commented
Ждём когда будет время апстрима

2024-10-27 20:12 UTC, KaiserMaus commented
Типо мех для космоса?

2024-10-30 07:07 UTC, VigersRay requested changes
Кооооооонфликты

2024-10-30 07:52 UTC, VigersRay approved these changes

2024-10-30 07:53 UTC, merged