Взрывной ошейник
space-sunrise/space-station-14 pull request #508
Opened 2024-10-13 18:21 UTC by pxc1984

Сделал взрывной ошейник по предложке из дискорда (https://discord.com/channels/1174575355370160190/1290973430002225203)

# Переформулировал предложку в нормальное ТЗ для себя:

"И только смерть разлучит нас.."

Букет (bouquet.rsi) - просто предметик
Красный ошейник (red_collar.rsi) - в соответствии с расшир. описанием
Белый ошейник (white_collar.rsi) - в соответствии с расшир. описанием
Инструкция - бумажонка с тем как привязывать ошейники

Коробочка с парными ошейниками:
- Красный ошейник
- Белый ошейник
- Букет
- Инструкция

Возможность купить коробочку с ошейниками в аплинке за 10 ТК.

Wires:
Болты - отвечает за возможность снять ошейник
Боевой режим - отвечает за то, взорвется ли ошейник
Электрошок - бьет током носителя при перерезании/пульсе
Убить - взрывает носителя со всеми вытекающими(плохой подбор слов) последствиями
+ 2 ничегонеделательных провода

Locale:
Ошейники связываются! (Кликнули красным ошейником по белому)
Ошейник уже привязан. (Кликнули красным ошейником по уже занятому белому)
Болты ошейника включаются! (Ошейник надето на кого-либо)
Ошейник переводится в боевой режим! (После того как красный ошейник надет на хоста И белый ошейник надет на носителя)
Зафиксирована смерть хоста! -> (3 секунды обратный отсчет) -> *Взрыв*
Боевой режим отключается! (Успешно провода перерезали)
Болты ошейника отключаются! (Перерезали провод болтов) -> можно снять
Пик! (Не успешно провода перерезали) -> *Взрыв*

Ошейники должны стоить по 3000 кредитов каждое

После того, как ошейник включили в первый раз, он теряет "девственность", и при снятии он уже будет не используемым.

# Чеклист
- [x] Сделать необходимые предметы.
- [x] Сделать связь между ошейниками.
- [ ] Наладить провода и дизарм ошейников.
- [ ] Cleanup и поиск багов.

2024-10-13 18:22 UTC, pxc1984 commented
линтеры падают не изза меня, ахах. Впервые!

2024-10-14 12:28 UTC, Rinary1 requested changes
спасибо за то что на этот раз без локализации в прототипах, но есть пару правок

2024-10-14 12:28 UTC, Rinary1 commented on Resources/Locale/ru-RU/_prototypes/_sunrise/entities/objects/devices/expcollar.ftl
через _, ftl файлы должны быть 1 в 1 по названию как файлы прототипов. Иначе с следующим крупным переводом создасться файл с правельным названием и будет конфликт.

2024-10-14 12:28 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Misc/bouquet.yml
А локализация где?
в Locale/ru-RU/entities/objects/misc/bouquet.ftl:
ent-bouquet = Букет
    .desc = Обычный душистый букет цветов.

2024-10-14 16:02 UTC, pxc1984 commented on Resources/Locale/ru-RU/_prototypes/_sunrise/entities/objects/devices/expcollar.ftl
Хм, не знал. Сделаю щас

2024-10-14 16:02 UTC, pxc1984 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Misc/bouquet.yml
чоооо, оно же работало на тестах.
Ему похуй на регистр получается? :choo:

2024-10-14 16:07 UTC, pxc1984 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Misc/bouquet.yml
ща

2024-10-18 14:31 UTC, pxc1984 commented
YAML Linter падает по причине, которую похоже нельзя исправить

2024-10-18 15:13 UTC, Rinary1 requested changes
иди работай

2024-10-18 15:13 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Devices/exp_collars.yml
> +    intesitySlope: 5
Гений всего мира, не пробовал исправить ошибку и уже ноет что не работает, всмотрись у тебя буквы N не хватает:
```suggestion
    intensitySlope: 5
```

2024-10-27 19:13 UTC, Rinary1 approved these changes

2024-10-30 07:08 UTC, VigersRay requested changes
Кооооооонфликты

2024-10-30 08:18 UTC, closed without merging

2024-10-30 08:18 UTC, VigersRay commented
Перезалито в https://github.com/space-sunrise/space-station-14/pull/567