Extended magazines
space-sunrise/space-station-14 pull request #509
Opened 2024-10-13 19:06 UTC by imskyhappy

:cl: SkyHappy
- add: Добавлены расширенные магазины

2024-10-14 05:40 UTC, Rinary1 commented on Resources/Prototypes/Research/arsenal.yml
> +  - MagazineDragunovExtended # Sunrise-end
Это надо в Resources/Prototypes/_Sunrise/Research/arsenal.yml

2024-10-14 05:40 UTC, Rinary1 requested changes
доделывай

2024-10-15 12:55 UTC, pxc1984 requested changes
Доделывай

2024-10-18 17:18 UTC, imskyhappy reviewed
доработал (если это не commit + push, то обидно.. (test plugins in VSC))

2024-10-30 07:08 UTC, merged