Рапира синдиката (Второй заход)
space-sunrise/space-station-14 pull request #517
Opened 2024-10-17 17:38 UTC by Focstor

## Кратное описание

Добавление рапиры синдиката в аплинк агентов
## По какой причине

Предложка https://discord.com/channels/1174575355370160190/1292216343172481034
## Медиа(Видео/Скриншоты)

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: Focstor
- add: Добавлена рапира синдиката.

2024-10-18 08:00 UTC, Rinary1 requested changes
переделывай локализацию

2024-10-18 08:00 UTC, Rinary1 commented on Resources/Locale/ru-RU/_prototypes/_sunrise/entities/clothing/belt/syndieSheath.ftl
ну и что это за хуйня? Не плодите локализации под каждый предмет, переноси нахуй  в belts.ftl

2024-10-18 08:00 UTC, Rinary1 commented on Resources/Locale/ru-RU/_prototypes/_sunrise/entities/objects/weapons/melee/syndicate_rapier.ftl
такая же хуйня, sword.ftl для кого?

2024-10-18 08:02 UTC, Rinary1 requested changes
пути до файлов не те

2024-10-18 08:02 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Clothing/Belt/belts.yml
> +    sprite: _SunRise/Clothing/Belt/syndie_sheath.rsi
путь не тот,
_Sunrise/Clothing/Belt/syndie_sheath.rsi

2024-10-18 08:02 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Clothing/Belt/belts.yml
> +    sprite: _SunRise/Clothing/Belt/syndie_sheath.rsi
путь не тот,
_Sunrise/Clothing/Belt/syndie_sheath.rsi

2024-10-18 08:02 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/sword.yml
> +    sprite: _SunRise/Objects/Weapons/Melee/syndicate_rapier.rsi
путь не тот,
_Sunrise/Objects/Weapons/Melee/syndicate_rapier.rsi

2024-10-18 08:02 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/sword.yml
> +    sprite: _SunRise/Objects/Weapons/Melee/syndicate_rapier.rsi
путь не тот,
_Sunrise/Objects/Weapons/Melee/syndicate_rapier.rsi

2024-10-18 11:29 UTC, Rinary1 approved these changes

2024-10-18 15:10 UTC, Rinary1 requested changes

2024-10-18 15:10 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/uplink_catalog.yml
> +  icon: { sprite: /Textures/_SunRise/Clothing/Belt/syndie_sheath.rsi, state: sheath-rapier }
аналогично к предидущим, путь дерьма

2024-10-18 15:10 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/sword.yml
> +    weight: 0.0002
этого уже давно нет

2024-10-19 09:45 UTC, Rinary1 approved these changes

2024-10-19 09:46 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/sword.yml
> -    weight: 0.0002
Епт, верни, я имел ввиду параметр "weight"

2024-10-19 16:58 UTC, Rinary1 approved these changes

2024-10-30 07:22 UTC, VigersRay requested changes
Коооооонфликты

2024-10-30 08:16 UTC, VigersRay commented
перезалито в https://github.com/space-sunrise/space-station-14/pull/565

2024-10-30 08:16 UTC, closed without merging