Фикс текста целей станций, - ру-символы из прототипов id карт и плащей
space-sunrise/space-station-14 pull request #518
Opened 2024-10-17 18:33 UTC by VoidVepayn

## Кратное описание
Повторный ПР с редакцией текста целей, плюс удаление текста на русском из прототипов id карт и плащей Sunrise'а.

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики.

2024-10-18 08:04 UTC, Rinary1 requested changes
убери это

2024-10-18 08:04 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Structures/Decoration/posters.yml
это всё конечно круто, но буквально ниже PR от меня фиксящий локализацию в yml файлах...

2024-10-18 08:04 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Devices/identification_cards.yml
это всё конечно круто, но буквально ниже PR от меня фиксящий локализацию в yml файлах...

2024-10-18 08:04 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Clothing/Neck/cloaks.yml
это всё конечно круто, но буквально ниже PR от меня фиксящий локализацию в yml файлах...

2024-10-18 14:34 UTC, pxc1984 commented
Ринари прав

2024-10-30 07:23 UTC, VigersRay requested changes
Коооооонфликты

2024-10-30 07:35 UTC, Rinary1 commented
> Коооооонфликты

они будут потому-что я писал)

2024-10-30 08:05 UTC, VigersRay commented
Перезалито в #564

2024-10-30 08:05 UTC, closed without merging