Medicine
space-sunrise/space-station-14 pull request #524
Opened 2024-10-18 13:27 UTC by Nrd-K

## Кратное описание
 Эти лекарства позволят лечить мертвым клеточный (Целлиминол) и радиационный (H-32)  урон

## По какой причине
 Лекарства, сделанные по предложениям из дс ласта "Новое лекарство" и "Новое криолекарство"
https://discord.com/channels/1253315855731916821/1287900163846967413
https://discord.com/channels/1253315855731916821/1292377059250667571

## Медиа(Видео/Скриншоты)

![Снимок экрана 2024-10-16 173113](https://github.com/user-attachments/assets/94fe07c3-dbf7-4756-8f5c-b77e43fafb3f)
![Снимок экрана 2024-10-16 173126](https://github.com/user-attachments/assets/438f50fa-3596-40af-8904-339d3940a94b)
![Снимок экрана 2024-10-16 173631](https://github.com/user-attachments/assets/8938a451-4392-4c95-84cb-5ee4da7f0683)
![Снимок экрана 2024-10-16 173715](https://github.com/user-attachments/assets/69b8aa62-7e12-4d9d-ba22-c19fb11f0a63)
![Снимок экрана 2024-10-16 173845](https://github.com/user-attachments/assets/81028446-72e7-43fc-bfac-2cf230d4cce8)
![Снимок экрана 2024-10-16 173857](https://github.com/user-attachments/assets/b938cc7e-a55d-46bb-906c-18b2e5eb06a4)
![Снимок экрана 2024-10-16 173931](https://github.com/user-attachments/assets/c4092308-5c9a-4a18-8f2c-fe969520ea88)
![Снимок экрана 2024-10-16 174143](https://github.com/user-attachments/assets/0558cb72-a93f-40fc-b230-231788b3774e)

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: Nrd
- add: Добавлен целлиминол и h-32

2024-10-18 13:28 UTC, Nrd-K commented
попытка номер 3

2024-10-18 14:33 UTC, pxc1984 commented on RobustToolbox
wtf.. оно точно должно менять сабмодуль?..

2024-10-18 14:33 UTC, pxc1984 approved these changes
Полезно и необходимо!

2024-10-18 17:36 UTC, SoulFN commented
Радиацию вроде и криоксадон лечит

2024-10-18 18:44 UTC, Nrd-K commented on RobustToolbox
Я без понятия откуда это появилось кстати, может просто ветка перезаписалась, оно появилось и как было просмотрено ни на что кроме изменения названия ветки вроде  не влияет, если оно и вправду на что то влияет и из за этого мне откажут я перезапишу всё заново без этого

2024-10-18 18:50 UTC, Nrd-K commented
> Радиацию вроде и криоксадон лечит

Лекарство не просто лечит радиацию, а лечит ее мёртвым

2024-10-19 17:00 UTC, Rinary1 requested changes

2024-10-19 17:00 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Reagents/fun.yml
> +             Cellular: -5
Это всё круто, но где баланс? Лекарство не сложно сварить, а дебаффов не имеет...

2024-10-19 20:21 UTC, Nrd-K commented on Resources/Prototypes/_Sunrise/Reagents/fun.yml
> +             Cellular: -5
Ну так некрозол тоже дебафов не имеет варится с температурой даже меньше чем у целлиминола, да и лечит множество других повреждений таких как физ, мех и яды, а тут целлиминол, что делается сложнее чем некрозол (Больше крови и докс) с большей чем он температурой и лечит только клеточные.
Что насчёт H-32, то лечение радиации у него по сравнению с аритразином уменьшена, в пример приведу тот же алоксадон, что делается из 22 единиц разных ингредиентов (примерно) за единицу, а H-32 из 13 единиц разных ингредиентов (примерно) за единицу. Алоксадон лечит термо электро и кислотные в общей сумме 7 повреждений, что довольно часто бывает у пассажиров, а H-32 только 2 единицы радиации, где радиации дай бог у трёх, четырех пассажиров будет, да и если и будет то меньше 50 уж точно.

2024-10-22 11:53 UTC, Nrd-K commented on Resources/Prototypes/_Sunrise/Reagents/fun.yml
> +             Cellular: -5
Кому лень читать:
По моим меркам баланс соблюдается благодаря:
-Сложности приготовления лекарства (Целлиминол)
-Частоте использования этих лекарств
(Целлиминол как и H-32 используются для лечения генетических и радиации соответственно, где этот урон появляется у экипажа довольно редко)
-Пониженной мощности лекарства относительно своего предшественника (H-32 относительно аритразина)

2024-10-22 13:37 UTC, Rinary1 approved these changes

2024-10-30 07:29 UTC, VigersRay commented
Переоткрыл #563

2024-10-30 07:29 UTC, closed without merging