Вендоматы для ОБР
space-sunrise/space-station-14 pull request #528
Opened 2024-10-18 19:26 UTC by DragonDidlo

## Кратное описание
В этом ПРе я предлагаю добавить 7 новых вендоматов для ОБР и хранилища скафандров ОБР.

**Вендоматы ЦК:**
- ОБР общий - (Наручники, фонарики, мониторы камер и т.п.)
- ОБР инж - (Инструменты и ресурсы)
- ОБР мед - (Медицинское снаряжение)
- ОБР пушки - (Стандартное вооружение ОБР)
- ОБР патроны - (Коробки с патронами)
- ОБР мехи - (Снаряга для мехов и их операторов)
- ОБР уборка - (Снаряжение для уборки и отчистки станции)

**Хранилища скафандров**
- Лидера ОБР
- Офицера ОБР
- Медика ОБР
- Инженера ОБР
- Уборщика ОБР

Так же добавлен 1 новый автоинъектор пулевых-повреждений:
Экспресс-доза пунктураза, физраствора и транексамовой кислоты, предназначенная для применения в боевых условиях.

## По какой причине
1. Отключили загрузку прототипов.
2. Для Маперов.
3. Для нового ЦК.
4. Для удобства ивентологам в спавне ОБР.

## Медиа(Видео/Скриншоты)
![image](https://github.com/user-attachments/assets/e2a66526-99fb-4d01-806d-aa26b24e6e99)

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**
:cl: Parashut
- add: Добавлено 7 новых Вендоматов и хранилища скафандров для ОБР.
- add: Добавлен медпен "автоинъектор пулевых-повреждений".

2024-10-18 22:57 UTC, KaiserMaus commented
Если посмотреть в руководстве в игре то вроде там написано что пунктураз сам по себе закрывает кровоток 
Если это так то стоит заменить транекс на эпинефрин(игнорирует замедление от урона)

2024-10-19 04:39 UTC, Mizeliy-2 commented
Задумка конечно хорошая мне понравилась, но как по мне не особо полезная, всё что нужно для обр шаттла я размещаю вручную в разные хранилища и ящики.

2024-10-19 16:44 UTC, Rinary1 commented
Я... Ждал этого момента, когда он выростет и не будет делать переводы в прототипах, я растроган. Меня хоть кто-то уважает и не надо пересматривать пр ради замечаний.

2024-10-19 16:51 UTC, Rinary1 requested changes
как бы я не хотел, но правки нужны. Замечательная идея но не очень реализация...

2024-10-19 16:51 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTMech.yml
> +    ClothingEyesHudDiagnostic: 2
Пересмотрите этот момент, сделай отдельное пнв нт с голубым цветом, пока что эквип можете оставить но вскоре я перенесу его в аплинк НТ.

2024-10-19 16:51 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTMech.yml
> +    MechEquipmentHorn: 1
Убрать, конечно круто, но никто не будет емагать шкаф обр.

2024-10-19 16:51 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTGuns.yml
> +    SpeedLoaderMagnumAP: 1
Такое же сомнительное решение, емаг шкафа не должен давать эквип синди

2024-10-19 16:51 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTEng.yml
> +    SprayPainter: 3
Убери краску из инженерного вендинга

2024-10-19 16:51 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTEng.yml
> +    SyndicateJawsOfLife: 1
Такое же сомнительное решение, емаг шкафа не должен давать эквип синди

2024-10-19 16:51 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTGuns.yml
> +    C4: 2
Раз сделал автомат с патронами, делай раздиление, пусть будет автомат только с оружием, для большых шаттлов где можно установить и оружейный и патронный и делай оружейный уже с патронами для малых шаттлов

2024-10-19 16:51 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTMed.yml
> +    PillAmbuzolPlus: 8
Никогда не думал что это много для обр? Они ведь не эс что-бы складывать им пол лекарств игры, тем более амбузол/амбузол+ который есть только у рхбзз и эс

2024-10-19 18:20 UTC, DragonDidlo commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTMech.yml
> +    ClothingEyesHudDiagnostic: 2
Смысла в новом ПНВ не вижу. Эти ПНВ нужны лишь для Операторов Мехов по большей части. У мехов же нету фонарика - вот им и альтернатива.

2024-10-19 18:21 UTC, DragonDidlo commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTGuns.yml
> +    C4: 2
Эти автоматы не для шаттлов предназначены. Они сделаны для оружейных расположенных на Аванпостах ДСО/ЦК. Смысла для шаттлов их делать я не вижу.
Сейчас у нас ОБР собираются именно на Аванпосте. Как только добавят пульт вызова ОБР (Автоматический без Админов), то тогда и будут уже Аплинки ОБР.

2024-10-19 18:22 UTC, DragonDidlo commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTMed.yml
> +    PillAmbuzolPlus: 8
Амбузол плюс уберу. Но обычный Амбузол думаю стоит оставить. Эти шкафы будут использовать не только ОБР но и РХБЗЗ.
Так же немного уменьшу кол-во медицины.

2024-10-19 18:25 UTC, DragonDidlo commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTMed.yml
> +    PillAmbuzolPlus: 8
При создании Вендомата - кол-во медицины было рассчитано на отряд до 8 человек.

2024-10-19 18:42 UTC, DragonDidlo commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTMed.yml
> +    PillAmbuzolPlus: 8
Амбузол убрал. Уменьшил кол-во медицины.

2024-10-19 18:42 UTC, DragonDidlo commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTEng.yml
> +    SprayPainter: 3
Это краскопульт для покраски шлюзов и труб

2024-10-19 18:42 UTC, DragonDidlo commented on Resources/Prototypes/_Sunrise/Catalog/VendingMachines/Inventories/ERTMech.yml
> +    ClothingEyesHudDiagnostic: 2
ПНВ убрал

2024-10-20 07:55 UTC, VigersRay commented
Ну вроде как у обр будут аплинки как у ЯО, потому в ПР должны остаться только новые вещи.

2024-10-20 15:54 UTC, DragonDidlo commented
> Ну вроде как у обр будут аплинки как у ЯО, потому в ПР должны остаться только новые вещи.

Так это нужно для маппинга ЦК. Да и пока ваши аплинки появятся...

2024-10-21 23:58 UTC, VigersRay commented
> > Ну вроде как у обр будут аплинки как у ЯО, потому в ПР должны остаться только новые вещи.
> 
> Так это нужно для маппинга ЦК. Да и пока ваши аплинки появятся...

ЦК не нужен, ЦК это будка 10 на 10 клеток с факсом и всё.

2024-10-23 07:03 UTC, CatBackGround commented
> > > Ну вроде как у обр будут аплинки как у ЯО, потому в ПР должны остаться только новые вещи.
> > 
> > Так это нужно для маппинга ЦК. Да и пока ваши аплинки появятся...
> 
> ЦК не нужен, ЦК это будка 10 на 10 клеток с факсом и всё.

Админ арена?

2024-10-25 10:17 UTC, DragonDidlo commented
> > > Ну вроде как у обр будут аплинки как у ЯО, потому в ПР должны остаться только новые вещи.
> > 
> > 
> > Так это нужно для маппинга ЦК. Да и пока ваши аплинки появятся...
> 
> ЦК не нужен, ЦК это будка 10 на 10 клеток с факсом и всё.

Это тебе он не нужен. Админы пользуются постоянно + игроки играют на Операторах ЦК.

2024-10-30 07:31 UTC, VigersRay commented
> > > > Ну вроде как у обр будут аплинки как у ЯО, потому в ПР должны остаться только новые вещи.
> > > 
> > > 
> > > Так это нужно для маппинга ЦК. Да и пока ваши аплинки появятся...
> > 
> > 
> > ЦК не нужен, ЦК это будка 10 на 10 клеток с факсом и всё.
> 
> Это тебе он не нужен. Админы пользуются постоянно + игроки играют на Операторах ЦК.

Из-за ЦК лагает весь сервер

2024-10-30 07:32 UTC, VigersRay commented
Пока что ждет добавления панели вызова ОБР, потом посмотрим

2024-11-11 15:44 UTC, closed without merging