Darvin7531
space-sunrise/space-station-14 pull request #529
Opened 2024-10-19 11:37 UTC by darvin7531

## Кратное описание

Добавить платок и головной убор для священника.

## По какой причине

Запрос игрока на добавление данных вещей.

## Медиа(Видео/Скриншоты)

https://ibb.co/72FNY0m
https://ibb.co/HYNj2G2

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**
:cl: darvin7531
- add: Добавлен Таллит и Шляпа с пейсами
- add: Таллит и Шляпа с пейсами добавлены в БогоМат

2024-10-19 16:43 UTC, Rinary1 requested changes
перевод в прототипах. Не принимать

2024-10-19 16:43 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Clothing/Head/hats.yml
> +  description: Чёрная шляпа с пейсами, обычно такую носят евреи.
Перевод в прототипе, переделывай. Оно должно быть на английском

2024-10-19 16:43 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Clothing/Neck/neck.yml
> +  description: Еврейский молитвенный платок.
Перевод в прототипе, переделывай. Оно должно быть на английском

2024-10-19 19:54 UTC, Rinary1 approved these changes

2024-10-21 15:06 UTC, CatBackGround commented
Таки кошерно...

2024-10-30 07:33 UTC, merged