better connection ui
space-sunrise/space-station-14 pull request #616
Opened 2024-11-06 08:08 UTC by rhailrake

![image](https://github.com/user-attachments/assets/44aedd52-319e-42b4-9474-aeeef954edaf)

2024-11-06 20:08 UTC, Rinary1 requested changes

2024-11-06 20:08 UTC, Rinary1 commented on Content.Client/Launcher/LauncherConnectingGui.xaml
> +                        <Label Text="Наше сообщество!"
Где локализация?

2024-11-06 20:08 UTC, Rinary1 commented on Content.Client/Launcher/LauncherConnectingGui.xaml
> +                        <Label Text="Присоединяйтесь к нам!"
Где локализация?

2024-11-06 20:08 UTC, Rinary1 commented on Content.Client/Launcher/LauncherConnectingGui.xaml
> +                                   Text="Сейчас играет: 0/0"
Где локализация?

2024-11-07 07:17 UTC, rhailrake commented on Content.Client/Launcher/LauncherConnectingGui.xaml
> +                                   Text="Сейчас играет: 0/0"
там так и было

2024-11-07 07:17 UTC, rhailrake commented on Content.Client/Launcher/LauncherConnectingGui.xaml
> +                                   Text="Сейчас играет: 0/0"
хочешь сделай епта

2024-11-07 07:22 UTC, Rinary1 commented on Content.Client/Launcher/LauncherConnectingGui.xaml
> +                                   Text="Сейчас играет: 0/0"
> хочешь сделай епта

Ну так потом сплик будет просить ибо англ сервер хочет, я этого делать не буду просто потому что ушел ПСЖ. И только делаю апстримы локализации

2024-11-13 01:10 UTC, VigersRay commented
Патом сделаю локализацию

2024-11-13 01:10 UTC, merged