Обновление брифинга Дракона
space-sunrise/space-station-14 pull request #628
Opened 2024-11-09 23:13 UTC by AverageNotDoingAnythingEnjoyer

## Кратное описание

Сделав спавн дракона вне станции, в брифинг Дракона была добавлена строка о направлении до станции. Данный PR просто обновляет локализацию брифинга Дракона.

## По какой причине

Чтобы челы не летали в поисках станции по 10 минут

## Медиа(Видео/Скриншоты)

<img width="1214" alt="Screenshot 2024-11-10 at 02 10 27" src="https://github.com/user-attachments/assets/4a987e90-ee9d-4771-a641-20dab900d9cd">

## Проверки

- [X] Я не требую помощи для завершения PR
- [X] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [X] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: J C Denton
- fix: Брифинг Дракона теперь сообщает направление до станции.

2024-11-13 01:15 UTC, VigersRay requested changes
Чел)))) Люди не знают где запад, сделай им или пинпоинтер в руку или указывай сторону (вверх, низ).

2024-11-13 11:49 UTC, AverageNotDoingAnythingEnjoyer commented
> Чел)))) Люди не знают где запад, сделай им или пинпоинтер в руку или указывай сторону (вверх, низ).

Да всмысли, эвак же указывает сторону каждый раунд, неужели не знают

2024-11-14 00:09 UTC, VigersRay commented
> > Чел)))) Люди не знают где запад, сделай им или пинпоинтер в руку или указывай сторону (вверх, низ).
> 
> Да всмысли, эвак же указывает сторону каждый раунд, неужели не знают

Не знают. Учти что еще люди камеру поворачивать любят.

2024-11-15 08:45 UTC, VigersRay commented
пу-пу-пу

2024-11-16 05:01 UTC, pxc1984 commented
Согласен с вигерсом

2024-12-11 01:45 UTC, VigersRay approved these changes

2024-12-11 01:45 UTC, merged