Supermatter copyright violation fix
space-sunrise/space-station-14 pull request #646
Opened 2024-11-16 05:32 UTC by pxc1984

Удаление суперматерии(закрывает https://github.com/space-sunrise/space-station-14/issues/643). Её никто не использует, а страйк может прилететь.

:cl: pacable
- remove: Суперматерия была удалена.

2024-11-17 01:26 UTC, VigersRay requested changes
На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.

2024-11-17 06:33 UTC, pxc1984 commented
> На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.

Лицензия на код. Прочитай issue от ринари.

2024-11-17 06:34 UTC, pxc1984 commented
> На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.

И да, я удалил камеру под СМ, она была только на meta стейшне

2024-11-18 07:48 UTC, Rinary1 commented
> На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.

![image](https://github.com/user-attachments/assets/d21fc81e-6dce-41a6-a704-7e68d02879fa)

Можете не удалять, автор даун

2024-11-18 07:58 UTC, VigersRay commented
> > На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.
> 
> Лицензия на код. Прочитай issue от ринари.

Если лицензия на код, зачем удалять прототипы?

2024-11-18 08:00 UTC, Rinary1 commented
> > > На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.
> > 
> > 
> > Лицензия на код. Прочитай issue от ринари.
> 
> Если лицензия на код, зачем удалять прототипы?

прототипы, текстуры и прочее тоже под лицензию попадает, просто они взяли текстуры и аудио у тг. А вот прототипы и код сами писали. Кстати тут в пр-е вырезают не только см, но и фикс рации и прочее мелкие фиксы.

2024-11-18 08:02 UTC, VigersRay commented
> > > > На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.
> > > 
> > > 
> > > Лицензия на код. Прочитай issue от ринари.
> > 
> > 
> > Если лицензия на код, зачем удалять прототипы?
> 
> прототипы, текстуры и прочее тоже под лицензию попадает, просто они взяли текстуры и аудио у тг. А вот прототипы и код сами писали. Кстати тут в пр-е вырезают не только см, но и фикс рации и прочее мелкие фиксы.

В чем проблема переписать под свои прототипы с сохранением ID сущностей?

2024-11-18 08:04 UTC, Rinary1 commented
> > > > > На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.
> > > > 
> > > > 
> > > > Лицензия на код. Прочитай issue от ринари.
> > > 
> > > 
> > > Если лицензия на код, зачем удалять прототипы?
> > 
> > 
> > прототипы, текстуры и прочее тоже под лицензию попадает, просто они взяли текстуры и аудио у тг. А вот прототипы и код сами писали. Кстати тут в пр-е вырезают не только см, но и фикс рации и прочее мелкие фиксы.
> 
> В чем проблема переписать под свои прототипы с сохранением ID сущностей?

хороший вопрос, но уже похуй, просто потому-что автор с нихуя доебался до нескольких репо

2024-11-18 08:42 UTC, AverageNotDoingAnythingEnjoyer commented
> > На некоторых картах уже сделали камеры под суперматерию, удалять её и возвращать обратно будет муторно, поэтому прототипы оставь. Не знаю на что там лицензия распространяется, если еще на спрайты то возьми их с сс13 на замену чтоль.
> 
> ![image](https://private-user-images.githubusercontent.com/72972221/387115029-d21fc81e-6dce-41a6-a704-7e68d02879fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTk2MTIsIm5iZiI6MTczMTkxOTMxMiwicGF0aCI6Ii83Mjk3MjIyMS8zODcxMTUwMjktZDIxZmM4MWUtNmRjZS00MWE2LWE3MDQtN2U2OGQwMjg3OWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4NDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MjMwNGQ2ZjQ1ZGU3ZTM3NDcwM2M3Yzk3ZWQ4OTczNTVkOTQwYTEyMzhjYmU1M2E5MTViY2FmNGY1MWFjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5AfuKt0ca7pRa6pkrggHsYV9O-V7F2PlP6FX7QOB97w)
> 
> Можете не удалять, автор гений

Так закрыто или как?

2024-11-18 13:55 UTC, VigersRay commented
очередная шиза ыы14

2024-11-18 13:55 UTC, closed without merging