Заставил скафы ЯО пропускать гипоспрей.
space-sunrise/space-station-14 pull request #652
Opened 2024-11-16 12:51 UTC by pxc1984

https://github.com/space-sunrise/space-station-14/issues/651

:cl: pacable
- fix: Гипоспрей медицинских боргов ЯО теперь могут прокалывать броню.

2024-11-16 13:14 UTC, kanopus952 commented
вроде в прототипе галочка на то, протыкает ли он броню. Добавь ее у гипо горлекса и гипоручки

2024-11-16 13:17 UTC, pxc1984 commented
> вроде в компоненте Hypospray галочка на то, протыкает ли он броню. Добавь ее у гипо горлекса и гипоручки

Долго мучаться. У каждого борга нестандартный гипоспрей. Проще сделать скафандры с отверстиями

2024-11-16 13:19 UTC, kanopus952 commented
> > вроде в компоненте Hypospray галочка на то, протыкает ли он броню. Добавь ее у гипо горлекса и гипоручки
> 
> Долго мучаться. У каждого борга нестандартный гипоспрей. Проще сделать скафандры с отверстиями

всмысле долго. Она по умолчанию в состоянии false у всех гипо. Стоит просто изменить на true у трех гипо: гипо мед борга синдиката, гипоспрея горлекса и гипоручки

2024-11-16 13:23 UTC, KaiserMaus commented
> > вроде в компоненте Hypospray галочка на то, протыкает ли он броню. Добавь ее у гипо горлекса и гипоручки
> 
> Долго мучаться. У каждого борга нестандартный гипоспрей. Проще сделать скафандры с отверстиями

Да это и сделали чтобы Борги станции НЕ кололи ЯО и не убивали их передозом.  
Дай просто пенетрейшен Яошным боргам и Гипоспрею

2024-11-17 01:24 UTC, VigersRay requested changes
Какой ужасный бред, т.е. то ради чего мы вырубили пробитие скафов просто вернулось обратно?
ГВ опять будет набирать ведра хлора и мутагена а после колоть ним ЯО.

Как вариант сделать гипоспрею синдиката пробитие скафов.

2024-11-17 06:51 UTC, pxc1984 commented
Ебануть не должно

2024-11-18 08:00 UTC, VigersRay requested changes
Ты добавил пробите скафов боргам, но что делать медику оперов?

2024-11-18 08:16 UTC, Rinary1 commented
> вроде в компоненте Hypospray галочка на то, протыкает ли он броню. Добавь ее у гипо горлекса и гипоручки

В чём тогда смысл дебаффа? Если 80% гипоспреев дадут возможность проникать через броню...

2024-11-18 08:16 UTC, Rinary1 commented
> Ты добавил пробите скафов боргам, но что делать медику оперов?

таблетки, везде должны быть дебаффы, в чем их смысл если их не будут использовать?

2024-11-19 15:17 UTC, VigersRay approved these changes

2024-11-19 15:17 UTC, merged