Теперь проще убирать следы
space-sunrise/space-station-14 pull request #720
Opened 2024-11-27 12:25 UTC by pxc1984

## Кратное описание

## По какой причине

https://discord.com/channels/1253315855731916821/1311213159146586113

## Медиа(Видео/Скриншоты)

https://github.com/user-attachments/assets/bf398330-773b-4836-b95a-b4e6fcbe7960

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: pacable
- fix: Упрощена уборка следов.

2024-11-27 12:26 UTC, pxc1984 commented
10 шакалов из 10

2024-11-27 12:29 UTC, KaiserMaus commented
Можешь тогда сразу увеличить лимит следов на тайле? 
Сейчас их после оптимизации реально мало и часто следы переписывают сами себя если ходить по луже в зад-вперёд

2024-11-27 12:31 UTC, pxc1984 commented
> Можешь тогда сразу увеличить лимит следов на тайле? Сейчас их после оптимизации реально мало и часто следы переписывают сами себя если ходить по луже в зад-вперёд
> 
> Все равно они имеют как авто удаление так и новые способы уборки

Думаю позже. Чем меньше засрана станция, тем больше хочется на ней играть)

2024-11-27 13:23 UTC, VigersRay commented
А смысл в этом если все уже отключили следы локально?

2024-11-27 13:26 UTC, KaiserMaus commented
> А смысл в этом если все уже отключили следы локально?

Им можно отключить отображение?
Но что на счёт тогда тех следов которые влияют на игру изменяя скорость?

2024-11-27 16:38 UTC, VigersRay commented
> > А смысл в этом если все уже отключили следы локально?
> 
> Им можно отключить отображение? Но что на счёт тогда тех следов которые влияют на игру изменяя скорость?

Они невидимые

2024-11-27 16:39 UTC, VigersRay commented
Короче в этом нету смысла пока следы можно отключать. Или убирай эту возможность или не надо делать уборку проще.
Еще стоит дать боргу уборщику возможность убирать следы проходя по ним.

2024-11-27 16:39 UTC, VigersRay requested changes
- Борг уборщик должен убирать следы проходя по ним
- Отключение видимости следов стоит удалить

2024-11-30 18:02 UTC, VigersRay commented
чейнжлог не соотвествует изменениям.

2024-12-01 14:51 UTC, VigersRay approved these changes

2024-12-01 14:53 UTC, merged