Поднятие лимита описания персонажей для особо общительных.
space-sunrise/space-station-14 pull request #751
Opened 2024-12-01 16:58 UTC by pxc1984

По предложке с ласт стейшна https://discord.com/channels/1253315855731916821/1310230025517273140

оказывается есть те, кому 512 - мало

:cl: pacable
- tweak: Поднято максимальное количество символов для описания персонажа до 800.

2024-12-01 17:55 UTC, Rinary1 commented
ты посмотрел как это будет выглядеть в игре? Зачем описание персонажа в 800 символов. Это никто читать не будет...

2024-12-01 18:08 UTC, VigersRay commented
> ты посмотрел как это будет выглядеть в игре? Зачем описание персонажа в 800 символов. Это никто читать не будет...
> 
> Это будет просто стена текста

Ну в том и прикол, игроки ласта в описании пишут не первое что видит игрок при осмотре игрока а буквально квенту с кучей говна

2024-12-01 21:00 UTC, kanopus952 commented
Нужно будет потом увеличить время отображения эмоутов над персонажем. Займусь мб. Очень неудобно что оно исчезает за 1.5 секунды примерно

2024-12-01 22:13 UTC, KaiserMaus commented
> Нужно будет потом увеличить время отображения эмоутов над персонажем. Займусь мб. Очень неудобно что оно исчезает за 1.5 секунды примерно

С шипением феленида от воды надо что-то делать

2024-12-01 23:01 UTC, VigersRay commented
> > Нужно будет потом увеличить время отображения эмоутов над персонажем. Займусь мб. Очень неудобно что оно исчезает за 1.5 секунды примерно
> 
> С шипением феленида от воды надо что-то делать

Мы решили удалить фелинидов так как они буквально тянуть весь сервер ниже лрп.

2024-12-01 23:05 UTC, KaiserMaus commented
> > > Нужно будет потом увеличить время отображения эмоутов над персонажем. Займусь мб. Очень неудобно что оно исчезает за 1.5 секунды примерно
> > 
> > 
> > С шипением феленида от воды надо что-то делать
> 
> Мы решили удалить фелинидов так как они буквально тянуть весь сервер ниже лрп.

Можно же собрать своих "феленидов" из условного дворфа+кошачьи ушки

2024-12-11 01:48 UTC, VigersRay requested changes
Нужен Cvar.

2025-01-04 06:53 UTC, VigersRay commented
Не актуально.

2025-01-04 06:53 UTC, closed without merging