Нерф зажигательных патронов
space-sunrise/space-station-14 pull request #778
Opened 2024-12-04 15:18 UTC by pxc1984

Удалил у зажигательных патронов моментальный урон и понизил их поджигательную эффективность. На настоящий момент они представляют собой лютую имбищу.

:cl: pacable
- tweak: Уменьшена поджигательность зажигательных боеприпасов.
- remove: Удален моментальный тепловой урон у зажигательных боеприпасов.

2024-12-04 16:55 UTC, KaiserMaus commented
Понизь лучше урон ожоговый при попадании и повысь стаки горения 
Они сильны как раз потому что это тупо лазер, люди почти не горят основной урон от попадания.
В безвоздушной среде патрон будет около бесполезным если сделать урон от стаков горения которые будут сразу пропадать

2024-12-05 12:01 UTC, VigersRay requested changes
Проджектайлы более не используются. Изменяй параметры хитскан вариаций зажигательных пуль.

2024-12-05 12:10 UTC, KaiserMaus commented
Если и менять их ттх то делать больше пассивно наносящий урон(Больше стаков горения за попадание меньше урона от прямого попадания), буквально сделает бесполезными в космосе и слабыми если рядом будет игрок с Огнетушителем коих много на станции

2024-12-12 00:49 UTC, VigersRay commented
ну вроде казер уже сделал отдельно это

2024-12-12 00:49 UTC, closed without merging