Малые балансные правки в мехов
space-sunrise/space-station-14 pull request #809
Opened 2024-12-07 21:34 UTC by KaiserMaus

## Кратное описание
Понизил рикошет у мехов боевых -5/10% 
Слегка Повысил скорострельность слабых лазеров и так же вернул скорострельность импульсного карабина меха добавив возможность вести огонь зажимая лкм

## По какой причине
Наныли 

## Медиа(Видео/Скриншоты)

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: KaiserMaus
- tweak: СyberSun начали экономить на броне МЕХов.
- tweak: NT улучшили некоторые лазеры для МЕХов.

2024-12-07 21:35 UTC, KaiserMaus commented
Эти Мерджи как то почистить можно или они меня будут преследовать до конца?....

2024-12-10 19:57 UTC, VigersRay requested changes

2024-12-10 19:57 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Эми не должен бить только в то что попадает, шоковый урон должен быть по области.

2024-12-10 19:57 UTC, VigersRay commented on Resources/Prototypes/_Sunrise/Catalog/uplink_catalog.yml
> +    stock: 2
Зачем 2? Тоже ставь 1. Не надо яо больше 3 мехов.

2024-12-10 20:26 UTC, KaiserMaus commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Удалил шок на ИОНке, отдельным PRом кто-то сделает

2024-12-11 01:46 UTC, VigersRay approved these changes

2024-12-11 01:47 UTC, merged