Mech Tweaks, Weapons Tweaks, Ressearch Tweaks.
space-sunrise/space-station-14 pull request #835
Opened 2024-12-12 23:15 UTC by KaiserMaus

## Кратное описание
Кратко не будет.
Дебафф Бр-64 3>2 скорострельность
Изменения Мг-42, смена калибра и количества патронов .30>.20  200>75
Повышения цены на Вооружение мехов
Дебафф пулемёта Дрейка
Изменения наполнения Мехов ОБР (Добавлена тяжелая Винтовка. фактически Бауер127 без прицела)
Пересмотр стоимости выстрела у Мехов, глобальное повышение для Тяжелого Вооружения (Ракетницы, дробовики)
Повышен заряд Ячейки синдиката с 8000 до  12400
Добавлена текстура для Ячейки Синдиката
Добавлена Ячейка ОБР. Аналогична ячейке Синдиката но  с другой тектурой
Добавлена Боевая Ячейка. 7200 заряда, ЭМИ имун. Т3 технология вместе с Дюрандом
Пересмотр ТТХ всех мехов, Тяжелый боевые мехи слегка были понерфлены. Мехи станции доведены до около уровня Боевых мехов ОБР/ЯО (Защита всё ещё хуже хоть и хп рядом)
Убран Алмаз из крафта Головы дюранда, может подстегну к его постройке
Везде со спавном Христов теперь будет лежать ИОНная пушка
Замена спавнера Бр64 на станциях на Ионную пушку
Замена спавнера Мк58 на Пистолет "Судья"
45 магнум теперь стреляет 25 укол 10 ушиб вместо 35 ушиб
## Добавлена краска для Маулера. МЯУЛЕР. 
(потом добавлю в безделушки аплинка)
Добавлен ящик с комплектом рефлект бронижелета. 
Содержит 2 жилета. 2 щита от лазеров. 2 энерго пушки. 3800
Удешевлён крафт пистолета СВАЛИН 5 золота > 2 золота
Убрана консоль управления шаттлом из шкафа Пилота
Заменен Дюранд на Оазисе на Рипли мк2 и балончик краски боевого рипли
Исследование Фазона требует наличия изученного Гигакса

## По какой причине

## Медиа(Видео/Скриншоты)
![image](https://github.com/user-attachments/assets/d5f23ece-e9cf-4760-b294-c04b8827c27d)
## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: KaiserMaus
- add: покраска меха в МЯУЛЕР.
- add: ящик рефлект брони в карго.
- add: энерго ячейка ОБР, боевая энерго Ячейка.
- tweak: Станции с тяжелым вооружением получили Ионную пушку.
- tweak: создание Дюранда упрощено.
- tweak: Живучесть всех мехов станции повышена.
- tweak: Исследование Фазона требует наличия изученного Гигакса.

2024-12-13 00:38 UTC, VigersRay requested changes
линтер

2024-12-13 02:16 UTC, VigersRay commented
Может сделать еще до кучи спрайт батареек синдиката?

2024-12-13 10:06 UTC, KaiserMaus commented
> Может сделать еще до кучи спрайт батареек синдиката?

Да сделаю, совсем забыл про них

2024-12-14 17:59 UTC, VigersRay approved these changes

2024-12-14 17:59 UTC, merged