Фикс рук фелинидов
space-sunrise/space-station-14 pull request #876
Opened 2024-12-17 17:26 UTC by Focstor

## Кратное описание

Пофиксил руки фелинидам. Они были перепутаны
## По какой причине

Ну типа баг и tasks-dev
## Медиа(Видео/Скриншоты)

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: Focsstor
- fix: Исправлены руки фелинидов.

2024-12-17 21:05 UTC, Focstor commented
> Ещё б у аркан починить.

Починю завтра

2024-12-18 13:44 UTC, Rinary1 requested changes

2024-12-18 13:44 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Body/Prototypes/demon.yml
> +    right_arm:
так и должно быть, ты хуйню делаешь, после такого у тебя перестанет работать хирургия.

Тебе ндао было просто поменять местами руки

2024-12-18 13:44 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Body/Prototypes/demon.yml
> +    left_foot:
так и должно быть, ты хуйню делаешь, после такого у тебя перестанет работать хирургия.

Тебе ндао было просто поменять местами руки

2024-12-18 13:44 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Body/Prototypes/felinid.yml
>        part: LeftFootHuman
так и должно быть, ты хуйню делаешь, после такого у тебя перестанет работать хирургия.

Тебе ндао было просто поменять местами руки

2024-12-18 13:46 UTC, Focstor commented on Resources/Prototypes/_Sunrise/Body/Prototypes/felinid.yml
>        part: LeftFootHuman
> так и должно быть, ты хуйню делаешь, после такого у тебя перестанет работать хирургия.
> 
> Тебе ндао было просто поменять местами руки

Пиздец, ну ладно, сейчас

2024-12-18 18:40 UTC, Rinary1 approved these changes

2024-12-21 15:03 UTC, merged