Фикс спрайта телескопички
space-sunrise/space-station-14 pull request #877
Opened 2024-12-17 19:03 UTC by Focstor

## Кратное описание

Фикс спрайта телескопички
## По какой причине

багрепорт
## Медиа(Видео/Скриншоты)

## Проверки

- [x] Я не требую помощи для завершения PR
- [x] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [x] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: Focstor
- fix: Телескопическая дубинка вновь отображается нормально.

2024-12-17 19:06 UTC, KaiserMaus commented
Спасибо, я всё думал когда починить

Может и щит (TelescopicShield) тогда починишь?

2024-12-18 13:45 UTC, Rinary1 requested changes

2024-12-18 13:45 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/telebaton.yml
> +        Blunt: 0
??? Что блять. Скаких пор телескопичка должна наносить 0 урона

2024-12-18 13:45 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/telebaton.yml
> +        Blunt: 3
????

2024-12-18 13:47 UTC, Focstor commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/telebaton.yml
> +        Blunt: 0
> ??? Что блять. Скаких пор телескопичка должна наносить 0 урона

Во включенном состоянии она же не должна наносить урона , так же было в тринашке

2024-12-18 14:03 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Entities/Objects/Weapons/Melee/telebaton.yml
> +        Blunt: 0
> > ??? Что блять. Скаких пор телескопичка должна наносить 0 урона
> 
> Во включенном состоянии она же не должна наносить урона , так же было в тринашке

а почему тогда есть урон в сложенном состоянии? Это бред, телескопичка это буквально стальной прут, она наносит ушибы людям

2024-12-18 18:40 UTC, Rinary1 approved these changes

2024-12-21 15:04 UTC, merged